# -*- coding: utf-8 -*-
"""INS alpha 0.3.5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15uGdgefWEXpkr5tCRzwUsJK-3_AvxfmJ
"""

import random

player_stats = {
    "health": 100,
    "gold": 0,
    "attack": 10
}

def print_intro():
    print("Welcome to Islands and Survival RPG!")
    print("You find yourself in a mysterious land. Your goal is to survive and thrive.")

def get_player_choice():
    print("What will you do?")
    print("1. Explore the forest")
    print("2. Rest at the campfire")
    print("3. Visit the shop")
    print("4. Fight a stronger monster")
    print("5. Search for a hidden cave")
    print("6. Train your skills")
    print("7. Challenge a fellow adventurer to a duel")
    print("8. Confront a mysterious entity")
    print("9. Visit the town")
    print("10. Quit the game")

    choice = input("Enter your choice (1-10): ")
    return choice

def explore_forest():
    print("You decide to explore the forest...")
    outcome = random.choice(["You discover a hidden treasure!", "You encounter a wild beast and escape narrowly.", "You find an ancient artifact that enhances your attack!"])
    print(outcome)
    if "treasure" in outcome:
        player_stats["gold"] += 20

def monster_attack():
    monster_health = random.randint(10, 30)
    print("A wild monster appears with {} health!".format(monster_health))

    while monster_health > 0:
        print("Your health: {}".format(player_stats["health"]))
        print("1. Attack")
        print("2. Run away")

        battle_choice = input("Enter your choice (1 or 2): ")
        if battle_choice == '1':
            player_damage = random.randint(5, 15)
            monster_health -= player_damage
            print("You deal {} damage to the monster!".format(player_damage))

            if monster_health > 0:
                monster_damage = random.randint(5, 10)
                player_stats["health"] -= monster_damage
                print("The monster attacks and deals {} damage to you!".format(monster_damage))
        elif battle_choice == '2':
            print("You manage to escape from the monster.")
            break
        else:
            print("Invalid choice. Please enter 1 or 2.")

        if player_stats["health"] <= 0:
            print("you wewe defeated by the monster, game over")
You were defeated by the monster. Game over.")
            break
        elif monster_health <= 0:
            print("You defeated the monster!")

def rest_at_campfire():
    print("You decide to rest at the campfire...")
    outcome = random.choice(["You feel refreshed and ready for more adventure!", "A mysterious figure approaches and shares valuable information.", "You have a vivid dream that increases your health!"])
    print(outcome)
    if "dream" in outcome:
        player_stats["health"] += 10

def visit_shop():
    print("Welcome to the shop!")
    print("You have {} gold.".format(player_stats["gold"]))
    print("1. Buy health potion (10 gold)")
    print("2. Buy sword (15 gold) - Increases attack")
    print("3. Buy armor (20 gold) - Reduces damage taken")
    print("4. Buy magic wand (25 gold) - Increases magic power")
    print("5. Buy potion of strength (15 gold) - Temporarily boosts attack")
    print("6. Buy shield (20 gold) - Reduces damage taken in battles")
    print("7. Buy enchanted amulet (30 gold) - Increases health and magic power")
    print("8. Buy fire scrolls (25 gold) - Unleashes a powerful fire attack")
    print("9. Buy poison dagger (20 gold) - Poisons enemies over time")
    print("10. Buy ice staff (30 gold) - Freezes enemies in battles")
    print("11. Buy teleportation crystal (40 gold) - Escape instantly from battles")
    print("12. Buy mystical elixir (35 gold) - Grants mysterious abilities")
    print("13. Leave the shop")

    choice = input("Enter your choice (1-13): ")
    if choice == '1' and player_stats["gold"] >= 10:
        print("You bought a health potion!")
        player_stats["health"] += 20
        player_stats["gold"] -= 10
    elif choice == '2' and player_stats["gold"] >= 15:
        print("You bought a sword! It increases your attack.")
        player_stats["attack"] += 10
        player_stats["gold"] -= 15
    elif choice == '3' and player_stats["gold"] >= 20:
        print("You bought armor! It reduces damage taken.")
        player_stats["gold"] -= 20
    elif choice == '4' and player_stats["gold"] >= 25:
        print("You bought a magic wand! It increases your magic power.")
        player_stats["gold"] -= 25
    elif choice == '5' and player_stats["gold"] >= 15:
        print("You bought a potion of strength! Your attack is temporarily boosted.")
        player_stats["attack"] += 15
        player_stats["gold"] -= 15
    elif choice == '6' and player_stats["gold"] >= 20:
        print("You bought a shield! It reduces damage taken in battles.")
        player_stats["gold"] -= 20
    elif choice == '7' and player_stats["gold"] >= 30:
        print("You bought an enchanted amulet! It increases your health and magic power.")
        player_stats["health"] += 30
        player_stats["attack"] += 10
        player_stats["gold"] -= 30
    elif choice == '8' and player_stats["gold"] >= 25:
        print("You bought fire scrolls! Unleashes a powerful fire attack.")
        player_stats["gold"] -= 25
    elif choice == '9' and player_stats["gold"] >= 20:
        print("You bought a poison dagger! It poisons enemies over time.")
        player_stats["gold"] -= 20
    elif choice == '10' and player_stats["gold"] >= 30:
        print("You bought an ice staff! Freezes enemies in battles.")
        player_stats["gold"] -= 30
    elif choice == '11' and player_stats["gold"] >= 40:
        print("You bought a teleportation crystal! Escape instantly from battles.")
        player_stats["gold"] -= 40
    elif choice == '12' and player_stats["gold"] >= 35:
        print("You bought a mystical elixir! Grants mysterious abilities.")
        player_stats["gold"] -= 35
    elif choice == '1' or choice == '2' or choice == '3' or choice == '4' or choice == '5' or choice == '6' or choice == '7' or choice == '8' or choice == '9' or choice == '10' or choice == '11' or choice == '12':
        print("You don't have enough gold.")
    elif choice != '13':
        print("Invalid choice. Please enter 1-13.")

def fight_stronger_monster():
    monster_health = random.randint(20, 40)
    print("You encounter a stronger monster with {} health!".format(monster_health))

    while monster_health > 0:
        print("Your health: {}".format(player_stats["health"]))
        print("1. Attack")
        print("2. Use a special move")
        print("3. Run away")

        battle_choice = input("Enter your choice (1, 2, or 3): ")
        if battle_choice == '1':
            player_damage = random.randint(10, 20)
            monster_health -= player_damage
            print("You deal {} damage to the stronger monster!".format(player_damage))

            if monster_health > 0:
                monster_damage = random.randint(5, 15)
                player_stats["health"] -= monster_damage
                print("The stronger monster attacks and deals {} damage to you!".format(monster_damage))
        elif battle_choice == '2':
            special_damage = random.randint(15, 25)
            monster_health -= special_damage
            print("You use a special move and deal {} damage to the stronger monster!".format(special_damage))
        elif battle_choice == '3':
            print("You try to run away but the stronger monster catches you.")
            break
        else:
            print("Invalid choice. Please enter 1, 2, or 3.")

        if player_stats["health"] <= 0:
            print("You were defeated by the stronger monster. Game over.")
            break
        elif monster_health <= 0:
            print("You defeated the stronger monster!")
            player_stats["gold"] += random.randint(15, 25)

def search_hidden_cave():
    print("You search for a hidden cave...")
    outcome = random.choice(["You discover a secret stash of gold!", "You find a mysterious portal and gain magical powers.", "You get trapped in a cave but manage to escape with minor injuries."])
    print(outcome)
    if "gold" in outcome:
        player_stats["gold"] += 30
    elif "powers" in outcome:
        player_stats["attack"] += 10

def train_skills():
    print("You decide to train your skills...")
    outcome = random.choice(["Your combat skills improve!", "You learn new magical abilities.", "You accidentally injure yourself during training but gain experience."])
    print(outcome)
    if "combat" in outcome:
        player_stats["attack"] += 5
    elif "magical" in outcome:
        player_stats["attack"] += 10

def challenge_duel():
    print("You challenge a fellow adventurer to a duel...")
    outcome = random.choice(["You win the duel and gain respect.", "The duel ends in a draw, and you both share tales of your adventures.", "You lose the duel but learn valuable combat strategies."])
    print(outcome)
    if "win" in outcome:
        player_stats["gold"] += 15
    elif "draw" in outcome:
        player_stats["health"] += 10
    elif "lose" in outcome:
        player_stats["attack"] += 5

def confront_mysterious_entity():
    print("You decide to confront a mysterious entity...")
    outcome = random.choice(["The entity grants you a powerful artifact!", "The entity challenges you to a mental duel and you emerge victorious.", "The entity tests your resolve, and you gain inner strength."])
    print(outcome)
    if "artifact" in outcome:
        player_stats["attack"] += 15
    elif "mental" in outcome:
        player_stats["health"] += 20
    elif "resolve" in outcome:
        player_stats["attack"] += 10

def visit_town():
    print("Welcome to the town!")
    print("1. Rest at the inn (10 gold) - Restores health")
    print("2. Visit the market - Explore available items")
    print("3. Participate in a festival - Gain gold and experience")
    print("4. Seek guidance at the temple - Receive blessings")
    print("5. Leave the town")

    choice = input("Enter your choice (1-5): ")
    if choice == '1' and player_stats["gold"] >= 10:
        print("You rest at the inn and feel rejuvenated!")
        player_stats["health"] += 30
        player_stats["gold"] -= 10
    elif choice == '1':
        print("You don't have enough gold.")
    elif choice == '2':
        visit_shop()
    elif choice == '3':
        festival_outcome = random.choice(["You win a talent show and gain 20 gold!", "You participate in a game and earn 15 gold!", "You enjoy the festivities and gain 10 gold and experience."])
        print(festival_outcome)
        if "gold" in festival_outcome:
            player_stats["gold"] += int(festival_outcome.split()[5])
        elif "experience" in festival_outcome:
            player_stats["attack"] += 5
        elif "talent" in festival_outcome:
            player_stats["gold"] += 20
    elif choice == '4':
        temple_outcome = random.choice(["You receive a blessing and gain 15 health!", "You meditate at the temple and gain 10 gold!", "The temple provides guidance, and you gain 10 experience."])
        print(temple_outcome)
        if "health" in temple_outcome:
            player_stats["health"] += int(temple_outcome.split()[7])
        elif "gold" in temple_outcome:
            player_stats["gold"] += int(temple_outcome.split()[7])
        elif "experience" in temple_outcome:
            player_stats["attack"] += 5
    elif choice != '5':
        print("Invalid choice. Please enter 1-5.")

def main():
    print_intro()

    while player_stats["health"] > 0:
        choice = get_player_choice()

        if choice == '1':
            explore_forest()
            monster_attack()
        elif choice == '2':
            rest_at_campfire()
        elif choice == '3':
            visit_shop()
        elif choice == '4':
            fight_stronger_monster()
        elif choice == '5':
            search_hidden_cave()
        elif choice == '6':
            train_skills()
        elif choice == '7':
            challenge_duel()
        elif choice == '8':
            confront_mysterious_entity()
        elif choice == '9':
            visit_town()
        elif choice == '10':
            print("Thanks for playing. Goodbye!")
            break
        else:
            print("Invalid choice. Please enter 1-11.")

if __name__ == "__main__":
    main()